## We only run this workflow on pushes to the master branch. This workflow will
## first determine if a release is to be published, and if so, build and publish.
## Otherwise, if not a release, we just perform CI build validation and deploy our
## storybook build to GH Pages.

name: Build and Release

on:
  push:
    branches:
      - master
    paths:
      - 'forge.json'
      - 'tsconfig.json'
      - '.eslintrc.json'
      - '.stylelintrc'
      - 'auto.config.ts'
      - '.github/workflows/**/*'
      - 'src/**/*'

concurrency: build-release-${{ github.ref }}

jobs:
  ## Initialize the workflow to gather configuration for subsequent jobs
  wf-config:
    name: Workflow Configuration
    uses: tyler-technologies/forge-automation-shared/.github/workflows/wf-configuration.yml@v0.10.1
    with:
      FILE_FILTERS: |
        build:
          - 'forge.json'
          - 'tsconfig.json'
          - '.eslintrc.json'
          - '.stylelintrc'
          - 'auto.config.ts'
          - '.github/workflows/**'
          - 'src/lib/**'
        test:
          - 'src/lib/**'
          - 'src/test/**'
        storybook:
          - 'src/lib/**'
          - 'src/stories/**'
    secrets:
      ARTIFACTORY_TOKEN: ${{ secrets.FORGE_ARTIFACTORY_TOKEN }}
      ARTIFACTORY_USERNAME: ${{ secrets.FORGE_ARTIFACTORY_USERNAME }}

  # This job will run on non-release builds for general CI validation only if files are changed that need to be built or tested
  build:
    name: Build and Test
    needs: wf-config
    uses: tyler-technologies/forge-automation-shared/.github/workflows/wf-build-and-test.yml@v0.10.0
    if: |
      ${{
        needs.wf-config.outputs.is-release == 'false' &&
        (
          contains(fromJson(needs.wf-config.outputs.file-changes || ''), 'build') ||
          contains(fromJson(needs.wf-config.outputs.file-changes || ''), 'test')
        )
      }}
    with:
      BUILD_ENABLED: ${{ contains(fromJson(needs.wf-config.outputs.file-changes || ''), 'build') }}
      TESTS_ENABLED: ${{ contains(fromJson(needs.wf-config.outputs.file-changes || ''), 'test') }}
    secrets:
      ARTIFACTORY_TOKEN: ${{ secrets.FORGE_ARTIFACTORY_TOKEN }}
      ARTIFACTORY_USERNAME: ${{ secrets.FORGE_ARTIFACTORY_USERNAME }}
      ARTIFACTORY_REGISTRY: ${{ secrets.FORGE_ARTIFACTORY_NPM_REGISTRY }}

  ## This job will run on release builds when publishing a new version
  build-and-release:
    name: Build and Release
    needs: wf-config
    uses: tyler-technologies/forge-automation-shared/.github/workflows/wf-build-release.yml@v0.10.0
    if: ${{ needs.wf-config.outputs.is-release == 'true' }}
    with:
      PRODUCTION_RELEASE: true
      NODE_VERSION: "14"
      TESTS_ENABLED: false ## We know the tests pass because they would have been triggered by a PR that requires tests so let's not waste time
      RELEASE_ENABLED: true
      BUILD_NPM_SCRIPT: "ci:build:all" ## We build the npm package and ALL static component bundles (this can take some time)
      PACKAGE_ASSETS_ARCHIVE_PATH: "dist/deployment-assets.tar.gz"
      PACKAGE_ASSETS_ENABLED: true
    secrets:
      GITHUB_APP_ID: ${{ secrets.TCP_AUTOMATION_APP_ID }}
      GITHUB_APP_KEY: ${{ secrets.TCP_AUTOMATION_APP_KEY }}
      ARTIFACTORY_TOKEN: ${{ secrets.FORGE_ARTIFACTORY_TOKEN }}
      ARTIFACTORY_USERNAME: ${{ secrets.FORGE_ARTIFACTORY_USERNAME }}
      ARTIFACTORY_REGISTRY: ${{ secrets.FORGE_ARTIFACTORY_NPM_REGISTRY }}

  ## This job will run only on release builds
  publish-cdn:
    name: Publish Components to CDN
    needs: [wf-config, build-and-release]
    uses: tyler-technologies/forge-automation-shared/.github/workflows/wf-publish-cloudfront-assets.yml@v0.10.0
    if: ${{ needs.wf-config.outputs.is-release == 'true' }}
    with:
      AWS_IAM_ROLE: "arn:aws:iam::505039608154:role/forge-prod-cdnmgmt-forge"
      AWS_REGION: "us-east-1"
      AWS_S3_BUCKET_NAME: "tylerforge-s3assets51e60022-1ols9p4m4dr5y"
      AWS_CLOUDFRONT_DISTRIBUTION_ID: "EDE7DVFI1X60B"
      MAX_CLOUDFRONT_INVALIDATIONS: 25

  ## We run this job only when files that effect Storybook are found in the changed files
  deploy-storybook:
    name: Deploy Storybook
    needs: wf-config
    uses: tyler-technologies/forge-automation-shared/.github/workflows/wf-publish-gh-pages.yml@v0.8.0
    if: ${{ contains(fromJson(needs.wf-config.outputs.file-changes) || '', 'storybook') }}
    with:
      PRODUCTION_RELEASE: true
      BUILD_DIRECTORY: dist/storybook
      BUILD_TARGET_DIRECTORY: docs/${{ github.head_ref || github.ref_name }}
      BUILD_NPM_SCRIPT: "ci:build-storybook"
      PR_COMMENT_HEADER: "View Storybook Deployment"
    secrets:
      GITHUB_DEPLOY_TOKEN: ${{ secrets.CORPDEV_GITHUB_ACCESS_TOKEN }}
      ARTIFACTORY_TOKEN: ${{ secrets.FORGE_ARTIFACTORY_TOKEN }}
      ARTIFACTORY_USERNAME: ${{ secrets.FORGE_ARTIFACTORY_USERNAME }}
